import { execSync, spawnSync } from 'child_process';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';

import { resolveRequiredString } from '../io';

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────

export type PullCheckResult =
  | { ok: true }
  | { ok: false; reason: 'auth' | 'denied' | 'other'; message: string };

export interface GhcrLoginResult {
  ok: boolean;
  message: string;
}

// ─────────────────────────────────────────────
// Task 5.1 — Preflight pull check
// ─────────────────────────────────────────────

export function checkImagePull(imageName: string): PullCheckResult {
  // Try to pull manifest only (faster than full pull)
  const result = spawnSync('docker', ['manifest', 'inspect', `${imageName}:latest`], {
    encoding: 'utf8',
    timeout: 15000,
  });

  if (result.status === 0) {
    return { ok: true };
  }

  const stderr = (result.stderr ?? '').toLowerCase();
  const stdout = (result.stdout ?? '').toLowerCase();
  const combined = stderr + stdout;

  if (combined.includes('unauthorized') || combined.includes('authentication required')) {
    return {
      ok: false,
      reason: 'auth',
      message: 'Authentication required — image is private and no credentials found.',
    };
  }

  if (combined.includes('denied') || combined.includes('forbidden')) {
    return {
      ok: false,
      reason: 'denied',
      message:
        'Access denied — credentials exist but lack required permissions (read:packages scope).',
    };
  }

  // Other failures (network, image not found, etc.) are non-blocking
  return {
    ok: false,
    reason: 'other',
    message: `Could not verify image access: ${(result.stderr ?? '').trim().slice(0, 200)}`,
  };
}

// ─────────────────────────────────────────────
// Task 5.2 — Interactive GHCR login wizard
// ─────────────────────────────────────────────

export async function runGhcrLoginWizard(
  imageName: string,
  defaultUsername?: string,
): Promise<GhcrLoginResult> {
  const registry = imageName.includes('ghcr.io') ? 'ghcr.io' : imageName.split('/')[0];

  process.stdout.write(`\n  Image requires authentication on ${registry}.\n`);
  process.stdout.write(
    '  You need a GitHub Personal Access Token (classic) with scope: read:packages\n',
  );
  process.stdout.write(
    '  Create one at: https://github.com/settings/tokens/new?scopes=read:packages\n\n',
  );

  const username = await resolveRequiredString(defaultUsername, `GitHub username`, defaultUsername);

  const token = await resolveRequiredString(undefined, 'GitHub token (input hidden)');

  // docker login
  const loginResult = spawnSync('docker', ['login', registry, '-u', username, '--password-stdin'], {
    input: token,
    encoding: 'utf8',
    timeout: 15000,
  });

  if (loginResult.status !== 0) {
    const errMsg = (loginResult.stderr ?? loginResult.stdout ?? '').trim();
    return {
      ok: false,
      message: `Login failed: ${errMsg}\n  Hint: ensure the token has the 'read:packages' scope.`,
    };
  }

  process.stdout.write(`  Login successful ✓\n`);

  // Re-check pull after login
  const pullCheck = checkImagePull(imageName);
  if (pullCheck.ok) {
    return { ok: true, message: 'Login successful and image is accessible.' };
  }

  if (!pullCheck.ok && pullCheck.reason === 'denied') {
    return {
      ok: false,
      message: [
        'Login succeeded but access is still denied.',
        '  This usually means:',
        "  - The token doesn't have 'read:packages' scope, or",
        '  - The package visibility requires org membership.',
        '  Check: GitHub → Organization → Packages → clash-hub-api → Package settings',
      ].join('\n'),
    };
  }

  // Other error after login — warn but don't block
  return {
    ok: true,
    message: `Login saved. Could not verify pull (${pullCheck.message}) — this may be a transient issue.`,
  };
}

// ─────────────────────────────────────────────
// Task 5.3 — Ensure docker config is mounted in webhook container
// ─────────────────────────────────────────────

export function ensureDockerConfigMounted(composeDir: string): boolean {
  const overridePath = join(composeDir, 'docker-compose.override.yml');
  const dockerConfigDir = join(homedir(), '.docker');

  // Check if override already mounts the docker config
  if (existsSync(overridePath)) {
    const content = readFileSync(overridePath, 'utf8');
    if (content.includes('.docker') || content.includes('docker/config')) {
      return false; // already configured
    }
  }

  // Create/append override
  const overrideContent = `# Auto-generated by depctl — mounts host docker credentials into webhook container
# so that 'docker compose pull' can authenticate against private registries (e.g. GHCR).
services:
  webhook:
    volumes:
      - ${dockerConfigDir}:/root/.docker:ro
`;

  writeFileSync(overridePath, overrideContent, 'utf8');
  return true; // newly created
}

// ─────────────────────────────────────────────
// Full preflight flow (used from repo-wizard)
// ─────────────────────────────────────────────

export async function runImagePreflight(opts: {
  imageName: string;
  defaultUsername?: string;
  composeDir: string;
  nonInteractive?: boolean;
}): Promise<void> {
  const check = checkImagePull(opts.imageName);

  if (check.ok) {
    process.stdout.write(`  Image accessible ✓\n`);
    ensureDockerConfigMounted(opts.composeDir);
    return;
  }

  if (check.reason === 'other') {
    // Non-blocking: warn and continue
    process.stdout.write(
      `  ⚠ Could not verify image access (${check.message}). Continuing anyway.\n`,
    );
    return;
  }

  // auth or denied
  if (opts.nonInteractive) {
    process.stderr.write(
      `  ⚠ Image requires authentication: ${check.message}\n` +
        `  Run 'docker login ghcr.io' manually on this host.\n`,
    );
    return;
  }

  // Interactive login wizard
  const loginResult = await runGhcrLoginWizard(opts.imageName, opts.defaultUsername);

  if (!loginResult.ok) {
    process.stderr.write(`\n  ⚠ ${loginResult.message}\n`);
    process.stderr.write('  You can retry later with: docker login ghcr.io\n\n');
  } else {
    // Ensure the docker config is mounted in the container for future pulls
    const mounted = ensureDockerConfigMounted(opts.composeDir);
    if (mounted) {
      process.stdout.write(
        `  Created docker-compose.override.yml to mount host credentials into webhook container.\n`,
      );
    }
  }
}
